/**
 * Mock data for development / demo purposes.
 * Replace API calls with real endpoints in production.
 */
import {Dare, User, LeaderboardEntry, Transaction} from '../types';

const now = new Date();
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000);
const inTwoDays = new Date(now.getTime() + 48 * 60 * 60 * 1000);
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    walletAddress: '0x04a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4',
    username: 'CryptoAthlete',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CryptoAthlete',
    bio: 'DeFi enthusiast & fitness fanatic 🏃',
    followersCount: 1240,
    followingCount: 380,
    daresCreated: 42,
    daresCompleted: 37,
    daresWon: 29,
    totalWinnings: '1250.50',
    successRate: 88,
    reputation: 4850,
    createdAt: '2024-01-15T10:00:00Z',
    isFollowing: false,
  },
  {
    id: 'u2',
    walletAddress: '0x05b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5',
    username: 'StarkDare',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=StarkDare',
    bio: 'Professional dare-taker 🎯',
    followersCount: 890,
    followingCount: 210,
    daresCreated: 28,
    daresCompleted: 22,
    daresWon: 19,
    totalWinnings: '890.00',
    successRate: 79,
    reputation: 3200,
    createdAt: '2024-02-20T10:00:00Z',
    isFollowing: true,
  },
  {
    id: 'u3',
    walletAddress: '0x06c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6',
    username: 'FitnessDegen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FitnessDegen',
    bio: 'I run for pizza 🍕',
    followersCount: 560,
    followingCount: 145,
    daresCreated: 15,
    daresCompleted: 13,
    daresWon: 10,
    totalWinnings: '340.00',
    successRate: 87,
    reputation: 2100,
    createdAt: '2024-03-10T10:00:00Z',
  },
];

export const MOCK_DARES: Dare[] = [
  {
    id: 'd1',
    creator: MOCK_USERS[0],
    title: 'Run 5km tomorrow before 8 AM',
    description:
      'I dare myself to run a full 5km before 8 AM tomorrow morning. Proof will be a Strava screenshot and a short video at the finish line.',
    category: 'fitness',
    status: 'open',
    visibility: 'public',
    creatorStake: '20.00',
    totalPool: '50.00',
    token: 'USDC',
    createdAt: now.toISOString(),
    startsAt: now.toISOString(),
    expiresAt: tomorrow.toISOString(),
    proofType: 'video',
    bets: [
      {
        id: 'b1',
        userId: 'u2',
        username: 'StarkDare',
        avatar: MOCK_USERS[1].avatar,
        prediction: 'fail',
        amount: '15.00',
        placedAt: now.toISOString(),
        txHash: '0xabc',
      },
      {
        id: 'b2',
        userId: 'u3',
        username: 'FitnessDegen',
        avatar: MOCK_USERS[2].avatar,
        prediction: 'success',
        amount: '15.00',
        placedAt: now.toISOString(),
        txHash: '0xdef',
      },
    ],
    betterCount: 2,
    successPool: '35.00',
    failPool: '15.00',
    votes: [],
    votesForSuccess: 0,
    votesForFail: 0,
    likeCount: 24,
    commentCount: 8,
    shareCount: 5,
    isLiked: false,
  },
  {
    id: 'd2',
    creator: MOCK_USERS[1],
    title: '100 push-ups in a row without stopping',
    description:
      'Live stream 100 consecutive push-ups. No breaks allowed. Single video proof.',
    category: 'fitness',
    status: 'proof_submitted',
    visibility: 'public',
    creatorStake: '50.00',
    totalPool: '145.00',
    token: 'USDC',
    createdAt: yesterday.toISOString(),
    startsAt: yesterday.toISOString(),
    expiresAt: now.toISOString(),
    votingEndsAt: inTwoDays.toISOString(),
    proofType: 'video',
    proof: {
      id: 'p1',
      type: 'video',
      uri: 'https://example.com/proof/d2.mp4',
      description: 'Completed 100 push-ups without stopping!',
      submittedAt: now.toISOString(),
      hash: 'Qm...',
    },
    bets: [
      {
        id: 'b3',
        userId: 'u1',
        username: 'CryptoAthlete',
        prediction: 'fail',
        amount: '50.00',
        placedAt: yesterday.toISOString(),
      },
      {
        id: 'b4',
        userId: 'u3',
        username: 'FitnessDegen',
        prediction: 'success',
        amount: '45.00',
        placedAt: yesterday.toISOString(),
      },
    ],
    betterCount: 2,
    successPool: '95.00',
    failPool: '50.00',
    votes: [
      {userId: 'u1', username: 'CryptoAthlete', vote: 'success', votedAt: now.toISOString()},
    ],
    votesForSuccess: 1,
    votesForFail: 0,
    likeCount: 87,
    commentCount: 23,
    shareCount: 14,
    isLiked: true,
  },
  {
    id: 'd3',
    creator: MOCK_USERS[2],
    title: 'Eat vegan for 7 days straight',
    description:
      "A full week of vegan diet. I'll document every meal with a photo posted to my social channel.",
    category: 'diet',
    status: 'completed',
    visibility: 'public',
    creatorStake: '30.00',
    totalPool: '90.00',
    token: 'USDC',
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    startsAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: yesterday.toISOString(),
    proofType: 'photo',
    proof: {
      id: 'p2',
      type: 'photo',
      uri: 'https://example.com/proof/d3.jpg',
      submittedAt: yesterday.toISOString(),
    },
    bets: [],
    betterCount: 3,
    successPool: '60.00',
    failPool: '30.00',
    votes: [],
    votesForSuccess: 5,
    votesForFail: 1,
    winner: 'success',
    rewardTxHash: '0x' + 'a'.repeat(64),
    likeCount: 156,
    commentCount: 42,
    shareCount: 31,
    isLiked: false,
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_USERS.map((user, i) => ({
  rank: i + 1,
  user,
  metric: i === 0 ? '37 completed' : i === 1 ? '22 completed' : '13 completed',
}));

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    hash: '0x' + 'a'.repeat(64),
    type: 'createDare',
    amount: '20.00',
    token: 'USDC',
    status: 'confirmed',
    timestamp: now.toISOString(),
    dareId: 'd1',
    dareTitle: 'Run 5km tomorrow before 8 AM',
  },
  {
    hash: '0x' + 'b'.repeat(64),
    type: 'receiveReward',
    amount: '85.50',
    token: 'USDC',
    status: 'confirmed',
    timestamp: yesterday.toISOString(),
    dareId: 'd3',
    dareTitle: 'Eat vegan for 7 days straight',
  },
];
